# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-02 08:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_userprofile_per_item_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='buy',
            name='already_given',
            field=models.BooleanField(default=False),
        ),
    ]
